'use client';
import dynamic from 'next/dynamic';
import { useMemo, useRef, useState } from 'react';
import { Activity, AlertTriangle, ChevronRight, Database, Download, Gauge, LayoutDashboard, Map, Network, RefreshCw, Search, ShieldCheck, Sparkles, TowerControl, TrendingUp, Upload, Zap } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { towerColumns, type TowerSite } from '../lib/tower-data';
import { calculateColocationScore, calculateInvestmentScore } from '../lib/scoring';
import { downloadJson } from '../lib/storage';
import IntelligenceAssistant from '../components/intelligence-assistant';
import VerticalBridgeBrand from '../components/vertical-bridge-brand';
import { useTowerPortfolio, type TowerSourceMode } from '../lib/use-tower-portfolio';

const PortfolioMap = dynamic(() => import('../components/portfolio-map'), { ssr: false });
type View = 'overview' | 'portfolio' | 'tower' | 'colocation' | 'investment' | 'maintenance' | 'energy' | 'future';
const nav = [
  { id: 'overview', label: 'Overview', icon: LayoutDashboard }, { id: 'portfolio', label: 'Portfolio', icon: Map },
  { id: 'tower', label: 'Tower 360', icon: TowerControl }, { id: 'colocation', label: 'Colocation', icon: Network },
  { id: 'investment', label: 'Investment', icon: TrendingUp }, { id: 'maintenance', label: 'Maintenance', icon: ShieldCheck },
  { id: 'energy', label: 'Energy', icon: Zap }, { id: 'future', label: 'Future Readiness', icon: Sparkles },
] as const;
const display = (value: number | null, suffix = '') => value === null ? 'Unknown' : `${Math.round(value * 100) / 100}${suffix}`;
const money = (value: number | null) => value === null ? 'Unknown' : new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value);
const bool = (value: boolean | null) => value === null ? 'Unknown' : value ? 'Yes' : 'No';
const average = (values: (number | null)[]) => { const known = values.filter((value): value is number => value !== null); return known.length ? known.reduce((sum, value) => sum + value, 0) / known.length : null; };

export default function Home() {
  const { sites, source, mode, setMode, loading, importing, error, configured, fetchedAt, refresh, importFile } = useTowerPortfolio();
  const [merge, setMerge] = useState(false);
  const [view, setView] = useState<View>('overview');
  const [selectedId, setSelectedId] = useState('');
  const [assistant, setAssistant] = useState(false);
  const input = useRef<HTMLInputElement>(null);
  const selected = sites.find((site) => site.id === selectedId) || sites[0];
  const stats = useMemo(() => ({ total: sites.length, healthy: sites.filter((site) => site.status === 'Healthy').length,
    attention: sites.filter((site) => site.status === 'Attention').length, critical: sites.filter((site) => site.status === 'Critical').length,
    expansion: sites.filter((site) => site.status === 'Expansion Opportunity').length, unknown: sites.filter((site) => site.status === 'Needs data').length }), [sites]);
  const openTower = (id: string) => { setSelectedId(id); setView('tower'); };
  const template = () => {
    const url = URL.createObjectURL(new Blob([`${towerColumns.join(',')}\n`], { type: 'text/csv' }));
    const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'vertical_bridge_tower_template.csv'; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  };
  const exportKml = async () => {
    const { towersToKml } = await import('../lib/tower-import');
    const url = URL.createObjectURL(new Blob([towersToKml(sites)], { type: 'application/vnd.google-earth.kml+xml' }));
    const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'vertical_bridge_towers.kml'; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  };
  return <div className="app-shell">
    <aside className="sidebar"><VerticalBridgeBrand product="Tower Intelligence" /><div className="workspace-label">PORTFOLIO COMMAND</div><nav aria-label="Tower navigation">{nav.map((item) => <button key={item.id} className={`nav-item ${view === item.id ? 'active' : ''}`} onClick={() => setView(item.id)}><item.icon size={17} /><span>{item.label}</span></button>)}</nav><div className="sidebar-bottom"><div className="demo-card"><div className="demo-dot" /><div><strong>{mode === 'live' && configured ? 'Connected tower feed' : mode === 'public' ? 'Public location snapshot' : 'Imported portfolio'}</strong><span>{sites.length.toLocaleString()} sites · {mode === 'live' ? '15-second polling' : 'Saved in this browser'}</span></div></div></div></aside>
    <main className="main"><header className="topbar"><div className="crumb"><span>Vertical Bridge</span><ChevronRight size={14} /><strong>{nav.find((item) => item.id === view)?.label}</strong></div><div className="top-actions"><label className="portfolio-select"><Database size={15} /><select aria-label="Tower data source" value={mode} disabled={importing} onChange={(event) => setMode(event.target.value as TowerSourceMode)}><option value="public">Vertical Bridge public locations</option><option value="live">Live data connection</option><option value="import">Imported portfolio</option></select></label><button className="icon-btn" disabled={loading || importing || mode === 'import'} onClick={refresh} aria-label="Refresh tower data"><RefreshCw size={17} /></button><span className="avatar">VB</span></div></header>
      <div className="content"><div className="page-header"><div><div className="eyebrow">Tower Intelligence</div><h1>{nav.find((item) => item.id === view)?.label === 'Overview' ? 'Your infrastructure, connected.' : nav.find((item) => item.id === view)?.label}</h1><p>{mode === 'live' ? fetchedAt ? `Last successful refresh: ${new Date(fetchedAt).toLocaleString()} · polls every 15 seconds` : 'Connecting to your configured tower feed.' : source ? `${source.name} · ${sites.length.toLocaleString()} locations` : 'Loading the public Vertical Bridge tower locations.'}</p></div><div className="data-actions"><button className="ask-button" disabled={!sites.length} onClick={() => setAssistant(true)}><Sparkles size={16} /> Ask Intelligence</button><button className="primary" disabled={importing} onClick={() => input.current?.click()}><Upload size={15} />{importing ? 'Importing…' : 'Import tower file'}</button></div></div>
        <div className="import-options"><label>Import behavior<select aria-label="Import behavior" value={merge ? 'merge' : 'replace'} onChange={(event) => setMerge(event.target.value === 'merge')}><option value="replace">Replace imported portfolio</option><option value="merge">Merge with current sites by ID</option></select></label><span>KML / KMZ · GeoJSON · CSV · JSON · up to 50 MB</span><a href="https://portal.verticalbridge.com/" target="_blank" rel="noreferrer">Open official site locator ↗</a></div>
        <input ref={input} hidden type="file" accept=".kml,.kmz,.geojson,.csv,.json,application/vnd.google-earth.kml+xml,application/vnd.google-earth.kmz,text/csv,application/json" onChange={(event) => { const file = event.target.files?.[0]; if (file) { setSelectedId(''); void importFile(file, merge); } event.target.value = ''; }} />
        {source && <div className="source-banner"><div><strong>{source.format === 'ArcGIS' ? 'HISTORICAL PUBLIC SNAPSHOT' : 'DATA SOURCE'} · {source.name}</strong><p>{source.warning || 'Locations and metrics shown are taken from this source.'}</p><small>{source.updatedAt && `Dataset edited ${new Date(source.updatedAt).toLocaleDateString()} · `}Loaded {new Date(source.importedAt).toLocaleString()}{source.publisher && ` · ${source.publisher}`}</small></div>{source.url && <a href={source.url} target="_blank" rel="noreferrer">View source ↗</a>}</div>}
        {loading && <p role="status">{mode === 'public' ? 'Loading all tower batches from the public Vertical Bridge layer…' : 'Refreshing connected tower data…'}</p>}
        {error && <div className="data-error" role="alert">{error}{mode === 'live' && fetchedAt && ' Showing the last successful snapshot.'}</div>}
        {!sites.length ? <Panel title={loading ? 'Loading tower locations…' : 'Connect your tower portfolio'}><div className="empty-state"><Database size={38} /><h2>Explore Vertical Bridge tower locations</h2><p>The public location layer loads automatically when no live feed is configured. You can also import a full KML/KMZ export from Google Earth Pro or Vertical Bridge's site locator.</p><div className="data-actions"><button className="primary" disabled={loading} onClick={() => { setMode('public'); refresh(); }}>Load Vertical Bridge towers</button><button className="ask-button" disabled={importing} onClick={() => input.current?.click()}>Import tower file</button><button className="ask-button" onClick={template}><Download size={15} /> CSV template</button></div><p>Google Earth Pro: right-click the tower folder → Save Place As → KML or KMZ. Export actual placemarks with coordinates.</p></div></Panel> : <>
          {view === 'overview' && (stats.unknown === stats.total ? <LocationOverview sites={sites} onOpen={openTower} /> : <><div className="kpi-grid"><Kpi label="Total sites" value={stats.total} icon={Map} /><Kpi label="Healthy sites" value={stats.healthy} icon={ShieldCheck} /><Kpi label="Sites requiring attention" value={stats.attention + stats.critical} icon={AlertTriangle} /><Kpi label="Expansion opportunities" value={stats.expansion} icon={TrendingUp} /><Kpi label="Incomplete metrics" value={stats.unknown} icon={Activity} /></div><div className="two-col"><Panel title="Portfolio status" subtitle="Calculated from the latest supplied metrics"><Chart data={Object.entries({ Healthy: stats.healthy, Attention: stats.attention, Critical: stats.critical, Expansion: stats.expansion, Unknown: stats.unknown }).map(([name, value]) => ({ name, value }))} /></Panel><Panel title="Portfolio signals"><Detail rows={[
            ['Average health', display(average(sites.map((site) => site.healthScore)), ' / 100')], ['Average structural utilization', display(average(sites.map((site) => site.structuralUtilization)), '%')], ['Average power utilization', display(average(sites.map((site) => site.powerUtilization)), '%')], ['Available tenant positions', sites.some((site) => site.availableTenantPositions !== null) ? String(sites.reduce((sum, site) => sum + (site.availableTenantPositions || 0), 0)) : 'Unknown'], ['Reported annual revenue', sites.some((site) => site.annualRevenue !== null) ? money(sites.reduce((sum, site) => sum + (site.annualRevenue || 0), 0)) : 'Unknown'],
          ]} /><p className="body-copy">Totals include reported values only; averages exclude missing metrics.</p></Panel></div><SiteTable sites={sites} onOpen={openTower} /></>)}
          {view === 'portfolio' && <><PortfolioMap sites={sites} selectedId={selected?.id || ''} onSelect={setSelectedId} onOpen={openTower} /><SiteTable sites={sites} onOpen={openTower} /></>}
          {(view === 'tower' || view === 'colocation') && selected && <><label className="tower-selector">Select tower<select value={selected.id} onChange={(event) => setSelectedId(event.target.value)}>{sites.map((site) => <option key={site.id} value={site.id}>{site.id} · {site.siteName}</option>)}</select></label>{view === 'tower' ? <Tower360 site={selected} refreshedAt={mode === 'live' ? fetchedAt : ''} onColocate={() => setView('colocation')} /> : <Colocation site={selected} />}</>}
          {view === 'investment' && <Investment sites={sites} onOpen={openTower} />}
          {view === 'maintenance' && <Maintenance sites={sites} onOpen={openTower} />}
          {view === 'energy' && <Energy sites={sites} onOpen={openTower} />}
          {view === 'future' && <Future sites={sites} onOpen={openTower} />}
          <div className="data-actions"><button className="ask-button" onClick={() => downloadJson('vertical_bridge_towers.json', { sites, source })}><Download size={15} /> Export portfolio</button><button className="ask-button" onClick={() => void exportKml()}><Map size={15} /> Export Google Earth KML</button><button className="ask-button" onClick={template}>CSV template</button></div>
        </>}
      </div>
    </main>{assistant && <IntelligenceAssistant sites={sites} source={source} onClose={() => setAssistant(false)} />}
  </div>;
}

function LocationOverview({ sites, onOpen }: { sites: TowerSite[]; onOpen: (id: string) => void }) {
  const counts = (key: 'state' | 'towerType') => Object.entries(sites.reduce((result, site) => { result[site[key]] = (result[site[key]] || 0) + 1; return result; }, {} as Record<string, number>)).map(([name, value]) => ({ name, value })).sort((a, b) => b.value - a.value);
  const states = counts('state'), types = counts('towerType');
  return <><div className="kpi-grid four"><Kpi label="Mapped tower locations" value={sites.length.toLocaleString()} icon={Map} /><Kpi label="States / territories reported" value={states.filter((item) => item.name !== 'Unknown').length} icon={Network} /><Kpi label="Reported structure types" value={types.filter((item) => item.name !== 'Unknown').length} icon={TowerControl} /><Kpi label="FCC ASR references" value={sites.filter((site) => !!site.asrNumber).length.toLocaleString()} icon={Database} /></div><div className="two-col"><Panel title="Tower locations by state" subtitle="Top 12 markets in the loaded source"><Chart data={states.slice(0, 12)} /></Panel><Panel title="Structure types" subtitle="Top reported types"><Chart data={types.slice(0, 8)} /></Panel></div><div className="location-note">Location intelligence is available now. Import operational data using “Merge with current sites by ID” to add power, occupancy, maintenance, energy and investment metrics.</div><SiteTable sites={sites} onOpen={onOpen} /></>;
}
function Tower360({ site, refreshedAt, onColocate }: { site: TowerSite; refreshedAt: string; onColocate: () => void }) {
  const headroom = site.powerCapacityKw !== null && site.powerUtilization !== null ? site.powerCapacityKw * (1 - site.powerUtilization / 100) : null;
  return <><div className="tower-hero"><div><div className="eyebrow">{site.id} · {site.siteName}</div><h2>{site.city}, {site.state}</h2><Status site={site} /></div><button className="primary" onClick={onColocate}><Network size={16} /> Evaluate colocation</button></div><div className="score-strip"><Score label="Health" value={site.healthScore} /><Score label="Expansion" value={site.expansionScore} /><Score label="Future readiness" value={site.futureReadinessScore} /><div className="tower-meta"><span>Source timestamp</span><strong>{site.updatedAt ? new Date(site.updatedAt).toLocaleString() : 'Not supplied'}</strong><small>{refreshedAt ? `Fetched ${new Date(refreshedAt).toLocaleTimeString()}` : 'Imported snapshot'}</small></div></div><div className="detail-grid">
    <Panel title="Site profile"><Detail rows={[["Tower type", site.towerType], ["Address", site.address || 'Not supplied'], ["ASR reference", site.asrNumber || 'Not supplied'], ["Height", display(site.height, ' ft')], ["Construction year", display(site.yearBuilt)], ["Ownership", site.ownershipType], ["Lease remaining", display(site.leaseYearsRemaining, ' years')], ["Coordinates", `${site.latitude}, ${site.longitude}`]]} /><div className="data-actions"><a className="site-link" href={`https://earth.google.com/web/search/${site.latitude},${site.longitude}`} target="_blank" rel="noreferrer">Open in Google Earth ↗</a><a className="site-link" href={`https://www.google.com/maps?q=${site.latitude},${site.longitude}`} target="_blank" rel="noreferrer">Google Maps ↗</a></div></Panel>
    <Panel title="Tenant / colocation"><Detail rows={[["Tenants", display(site.tenants)], ["Maximum tenants", display(site.maxTenants)], ["Available positions", display(site.availableTenantPositions)], ["Structural utilization", display(site.structuralUtilization, '%')], ["Equipment space", site.equipmentSpace], ["Power headroom", display(headroom, ' kW')]]} /></Panel>
    <Panel title="Power"><Detail rows={[["Capacity", display(site.powerCapacityKw, ' kW')], ["Utilization", display(site.powerUtilization, '%')], ["Peak utilization", display(site.peakPowerUtilization, '%')], ["Battery backup", display(site.batteryBackupHours, ' hours')], ["Generator available", bool(site.generatorAvailable)]]} /></Panel>
    <Panel title="Connectivity"><Detail rows={[["Fiber available", bool(site.fiberAvailable)], ["Backhaul", display(site.backhaulCapacityGbps, ' Gbps')], ["Latency", display(site.latencyMs, ' ms')], ["Demand", site.networkDemand]]} /></Panel>
    <Panel title="Financials"><Detail rows={[["Monthly revenue", money(site.monthlyRevenue)], ["Annual revenue", money(site.annualRevenue)], ["Supplied revenue opportunity", money(site.potentialRevenue)]]} /></Panel>
    <Panel title="Operations"><Detail rows={[["Last inspection", site.lastInspection || 'Unknown'], ["Open work orders", display(site.openWorkOrders)], ["Maintenance risk", site.maintenanceRisk], ["Monthly energy", display(site.energyConsumption, ' kWh')]]} /><p className="body-copy">{site.finding || 'No inspection finding supplied.'}</p></Panel>
    {!!site.dataSource && <Panel title="Location source"><p className="body-copy">{site.dataSource}{site.sourceUpdatedAt && ` · Dataset edited ${new Date(site.sourceUpdatedAt).toLocaleDateString()}`}</p>{site.sourceUrl && <a className="site-link" href={site.sourceUrl} target="_blank" rel="noreferrer">View original source ↗</a>}<details><summary>Original source attributes</summary><Detail rows={Object.entries(site.sourceProperties || {}).map(([key, value]) => [key, value === null ? 'Not supplied' : String(value)])} /></details></Panel>}
  </div></>;
}
function Colocation({ site }: { site: TowerSite }) {
  const score = calculateColocationScore(site);
  const check = (value: number | null, test: (n: number) => boolean) => value === null ? null : test(value);
  const checks: [string, boolean | null][] = [['Structural utilization below 85%', check(site.structuralUtilization, (n) => n < 85)], ['Power utilization below 82%', check(site.powerUtilization, (n) => n < 82)], ['Available tenant position', check(site.availableTenantPositions, (n) => n > 0)], ['Equipment space', site.equipmentSpace === 'Unknown' ? null : site.equipmentSpace !== 'Limited'], ['Backhaul at least 2 Gbps', check(site.backhaulCapacityGbps, (n) => n >= 2)], ['Lease remaining at least 3 years', check(site.leaseYearsRemaining, (n) => n >= 3)]];
  return <div className="two-col"><Panel title="Colocation feasibility" subtitle={`Assessment of ${site.id}`}><Score label={score === null ? 'Missing required metrics' : score >= 75 ? 'Potentially suitable' : score >= 55 ? 'Needs review' : 'Capacity constraints'} value={score} /><div className="check-list">{checks.map(([label, pass]) => <div key={label}><span>{label}</span><b className={pass ? 'pass' : 'warn'}>{pass === null ? 'UNKNOWN' : pass ? 'PASS' : 'REVIEW'}</b></div>)}</div><p className="body-copy">The score uses structural and power headroom, tenant positions, equipment space, backhaul, lease duration and health.</p></Panel><Panel title="Deployment context"><Detail rows={[["Site", site.siteName], ["Available positions", display(site.availableTenantPositions)], ["Structural utilization", display(site.structuralUtilization, '%')], ["Power utilization", display(site.powerUtilization, '%')], ["Revenue opportunity supplied", money(site.potentialRevenue)]]} /><p className="body-copy">{site.recommendation || 'No deployment recommendation was supplied with this site.'}</p></Panel></div>;
}
function Investment({ sites, onOpen }: { sites: TowerSite[]; onOpen: (id: string) => void }) {
  const ranked = sites.filter((site) => calculateInvestmentScore(site) !== null).sort((a, b) => (calculateInvestmentScore(b) || 0) - (calculateInvestmentScore(a) || 0));
  const markets = Object.entries(ranked.slice(0, 20).reduce((result, site) => { result[site.state] = (result[site.state] || 0) + 1; return result; }, {} as Record<string, number>)).map(([name, value]) => ({ name, value })).sort((a, b) => b.value - a.value);
  return <><div className="two-col"><Panel title="Opportunity by market" subtitle="Top 20 scored sites"><Chart data={markets} /></Panel><Panel title="Investment model"><Detail rows={[["Expansion opportunity", '25%'], ["Available capacity", '20%'], ["Supplied revenue opportunity", '15%'], ["Future readiness", '15%'], ["Lease duration", '10%'], ["Site health", '10%'], ["Power headroom", '5%']]} /><p className="body-copy">{sites.length - ranked.length} sites lack the metrics needed for a complete investment score.</p></Panel></div><SiteTable sites={ranked} onOpen={onOpen} score={calculateInvestmentScore} scoreLabel="Investment" /></>;
}
function Maintenance({ sites, onOpen }: { sites: TowerSite[]; onOpen: (id: string) => void }) {
  const [filter, setFilter] = useState('All');
  const risks = sites.filter((site) => site.riskScore !== null && site.maintenanceRisk !== 'Low');
  const groups = Object.entries(risks.reduce((result, site) => { result[site.riskType] = (result[site.riskType] || 0) + 1; return result; }, {} as Record<string, number>)).map(([name, value]) => ({ name, value }));
  const filtered = risks.filter((site) => filter === 'All' || site.riskType === filter).sort((a, b) => (b.riskScore || 0) - (a.riskScore || 0));
  return <><div className="kpi-grid four"><Kpi label="High risk" value={sites.filter((site) => site.maintenanceRisk === 'High').length} icon={AlertTriangle} /><Kpi label="Medium risk" value={sites.filter((site) => site.maintenanceRisk === 'Medium').length} icon={Activity} /><Kpi label="Unknown risk" value={sites.filter((site) => site.maintenanceRisk === 'Unknown').length} icon={Gauge} /><Kpi label="Reported work orders" value={display(sites.some((site) => site.openWorkOrders !== null) ? sites.reduce((sum, site) => sum + (site.openWorkOrders || 0), 0) : null)} icon={ShieldCheck} /></div><Panel title="Current maintenance signals by type" subtitle="Latest snapshot, based on supplied operational metrics"><Chart data={groups} /><div className="filter-tabs">{['All', ...groups.map((group) => group.name)].map((value) => <button key={value} className={filter === value ? 'selected' : ''} onClick={() => setFilter(value)}>{value}</button>)}</div></Panel><SiteTable sites={filtered} onOpen={onOpen} score={(site) => site.riskScore} scoreLabel="Risk" /><p className="body-copy">Risk reflects current utilization, work orders and backup-power metrics.</p></>;
}
function Energy({ sites, onOpen }: { sites: TowerSite[]; onOpen: (id: string) => void }) {
  const known = sites.filter((site) => site.energyConsumption !== null);
  const markets = Object.entries(known.reduce((result, site) => { result[site.state] = (result[site.state] || 0) + (site.energyConsumption || 0); return result; }, {} as Record<string, number>)).map(([name, value]) => ({ name, value: Math.round(value / 1000 * 100) / 100 })).sort((a, b) => b.value - a.value);
  return <><div className="kpi-grid four"><Kpi label="Reported monthly consumption" value={display(known.length ? known.reduce((sum, site) => sum + (site.energyConsumption || 0), 0) / 1000 : null, ' MWh')} icon={Zap} /><Kpi label="Average reported efficiency" value={display(average(sites.map((site) => site.energyEfficiencyScore)), ' / 100')} icon={Gauge} /><Kpi label="Sites reporting energy" value={known.length} icon={Activity} /><Kpi label="Missing energy readings" value={sites.length - known.length} icon={AlertTriangle} /></div><Panel title="Monthly consumption by market" subtitle="MWh from supplied energy readings"><Chart data={markets} /></Panel><SiteTable sites={[...known].sort((a, b) => (b.energyConsumption || 0) - (a.energyConsumption || 0))} onOpen={onOpen} score={(site) => site.energyConsumption} scoreLabel="kWh / month" /></>;
}
function Future({ sites, onOpen }: { sites: TowerSite[]; onOpen: (id: string) => void }) {
  const ranked = sites.filter((site) => site.futureReadinessScore !== null).sort((a, b) => (b.futureReadinessScore || 0) - (a.futureReadinessScore || 0));
  return <><Panel title="Infrastructure readiness dimensions"><Detail rows={[["Power", 'Available power headroom'], ["Connectivity", 'Fiber and backhaul capacity'], ["Physical capacity", 'Structural headroom and equipment space'], ["Expansion", 'Tenant positions and network demand']]} /><p className="body-copy">{sites.length - ranked.length} sites are missing readiness inputs. Readiness is a calculated planning score.</p></Panel><SiteTable sites={ranked} onOpen={onOpen} score={(site) => site.futureReadinessScore} scoreLabel="Readiness" /></>;
}
function SiteTable({ sites, onOpen, score = (site) => site.healthScore, scoreLabel = 'Health' }: { sites: TowerSite[]; onOpen: (id: string) => void; score?: (site: TowerSite) => number | null; scoreLabel?: string }) {
  const [query, setQuery] = useState('');
  const [page, setPage] = useState(0);
  const filtered = sites.filter((site) => `${site.id} ${site.siteName} ${site.city} ${site.state}`.toLowerCase().includes(query.toLowerCase()));
  const safePage = Math.min(page, Math.max(0, Math.ceil(filtered.length / 50) - 1));
  const locationsOnly = scoreLabel === 'Health' && sites.every((site) => site.healthScore === null);
  return <Panel title="Tower portfolio" subtitle={`${filtered.length.toLocaleString()} sites`} action={<label className="table-search"><Search size={14} /><input aria-label="Search tower portfolio" placeholder="Search sites…" value={query} onChange={(event) => { setQuery(event.target.value); setPage(0); }} /></label>}>
    <div className="table-wrap"><table><thead><tr><th>Site</th><th>Market</th>{locationsOnly ? <><th>Structure type</th><th>ASR reference</th><th>Coordinates</th></> : <><th>{scoreLabel}</th><th>Structure</th><th>Power</th><th>Positions</th><th>Status</th></>}</tr></thead><tbody>{filtered.slice(safePage * 50, safePage * 50 + 50).map((site) => <tr key={site.id}><td><button className="site-link" onClick={() => onOpen(site.id)}>{site.id}</button><small>{site.siteName}</small></td><td>{site.city}, {site.state}</td>{locationsOnly ? <><td>{site.towerType}</td><td>{site.asrNumber || 'Not supplied'}</td><td>{site.latitude.toFixed(5)}, {site.longitude.toFixed(5)}</td></> : <><td>{display(score(site))}</td><td>{display(site.structuralUtilization, '%')}</td><td>{display(site.powerUtilization, '%')}</td><td>{display(site.availableTenantPositions)}</td><td><Status site={site} /></td></>}</tr>)}</tbody></table></div>
    {!filtered.length && <p>No sites with matching data.</p>}{filtered.length > 50 && <div className="data-actions"><button className="ask-button" disabled={!safePage} onClick={() => setPage(safePage - 1)}>Previous</button><span>Page {safePage + 1} of {Math.ceil(filtered.length / 50)}</span><button className="ask-button" disabled={(safePage + 1) * 50 >= filtered.length} onClick={() => setPage(safePage + 1)}>Next</button></div>}
  </Panel>;
}
function Status({ site }: { site: TowerSite }) { return <span className={`status-pill ${site.status.toLowerCase().replaceAll(' ', '-')}`}>{site.status}</span>; }
function Panel({ title, subtitle, children, action }: { title: string; subtitle?: string; children: React.ReactNode; action?: React.ReactNode }) { return <section className="panel"><div className="panel-head"><div><h2>{title}</h2>{subtitle && <span>{subtitle}</span>}</div>{action}</div>{children}</section>; }
function Kpi({ label, value, icon: Icon }: { label: string; value: number | string; icon: typeof Map }) { return <div className="kpi"><div className="kpi-icon blue"><Icon size={18} /></div><div className="kpi-label">{label}</div><div className="kpi-value">{value}</div></div>; }
function Detail({ rows }: { rows: string[][] }) { return <div className="detail-rows">{rows.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>; }
function Score({ label, value }: { label: string; value: number | null }) { return <div className="score"><span>{label}</span><strong>{display(value)}{value !== null && <small>/100</small>}</strong><div className="progress"><i style={{ width: `${value || 0}%` }} /></div></div>; }
function Chart({ data }: { data: { name: string; value: number }[] }) { return data.length ? <ResponsiveContainer width="100%" height={230}><BarChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" /><YAxis /><Tooltip /><Bar dataKey="value" fill="#477de0" radius={[3, 3, 0, 0]} /></BarChart></ResponsiveContainer> : <p>No reported data for this chart.</p>; }
